const squares: string[] = [
  `Loads are fact`,
  `"I hate users" - Dustin`,
  `Becca is scowling`,
  `Aaron shows The Chart`,
  `Strata Cake`,
  `Tiny electrical brain`,
  `Strata-sphere`,
  `Strata-gy`,
  `The data is out there`,
  `Yes to all of that`,
  `Aaron says no but in a really likable way`,
  `Early access`,
  `Bob's your uncle`,
  `Cannibalize our core business`,
  `Aaron winks at you`,
  `Sears vs Amazon`,
  `Blockbuster vs Netflix`,
  `"I love efficiency" - Dustin`,
  `Whiplash`,
  `Aaron is being annoying`,
  `Exosphere?`,
  `Faster horse`,
  `Digital dumbass`,
  `Rooftop units go on the roof`,
  `Architects don't give a shit about anything`,
  `De-risk`,
  `Ed is being annoying`,
  `We can back into it`,
  `Never silly`,
  `Justin Older!!`,
  `Envelope`,
  `Vibe data`,
  `Churn`,
  `Aaron hates the design`,
];

export default squares;
